name: core_navigation
description: This package contains all navigation related
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core_dependencies:
    path: '../../core/core_dependencies'

  feature_welcome:
    path: '../../feature/feature_welcome'

  feature_currencies_list:
    path: '../../feature/feature_currencies_list'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
