name: core_test
description: Common testing class and utilities
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core_dependencies:
    path: '../core_dependencies'

  core_network:
    path: '../core_network'

  core_data:
    path: '../core_data'

  core_commons:
    path: '../core_commons'

  core_domain:
    path: '../core_domain'

  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
