name: core_domain
description: Domain and bussines rules for the project
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core_dependencies:
    path: '../core_dependencies'

  core_commons:
    path: '../core_commons'

  core_data:
    path: '../core_data'

  core_test:
    path: '../core_test'

  core_network:
    path: '../core_network'

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3

flutter:
