name: core_dependency_injection
description: Dependency injection manager
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core_dependencies:
    path: '../core_dependencies'

  core_data:
    path: '../core_data'

  core_network:
    path: '../core_network'

  core_domain:
    path: '../core_domain'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3

flutter:
