name: flutter_currency_micro_app
description: Currency App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core_dependencies:
    path: "../packages/core/core_dependencies"

  core_dependency_injection:
    path: "../packages/core/core_dependency_injection"

  core_navigation:
    path: "../packages/core/core_navigation"

  feature_welcome:
    path: "../packages/feature/feature_welcome"

  feature_conversion:
    path: "../packages/feature/feature_conversion"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
