name: flutter_currency_micro_app
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  feature_welcome:
    path: '../packages/feature/feature_welcome'

  feature_conversion:
    path: '../packages/feature/feature_conversion'

  feature_currencies_list:
    path: '../packages/feature/feature_currencies_list'

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
