name: feature_conversion
description: Feature module for currency conversion
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core_domain:
    path: '../../core/core_domain'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
