name: feature_currencies_list
description: Currencies list feature for the app
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core_commons:
    path: '../../core/core_commons'

  core_dependencies:
    path: '../../core/core_dependencies'

  core_domain:
    path: '../../core/core_domain'

  core_ui:
    path: '../../core/core_ui'

  core_dependency_injection:
    path: '../../core/core_dependency_injection'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3

flutter: