name: core_dependencies
description: Common dependencies for the whole project
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  chopper: ^6.0.0

  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
